// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxzinqbrtwqtpzfevanh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4emlucWJydHdxdHB6ZmV2YW5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MzQxNTYsImV4cCI6MjA3MjQxMDE1Nn0.3S-_B1DC2hBY1cWcy9GQVdYeq_oygKnrR8XieNbrYJY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});